SIZE = (800, 600)
CENTRE = (400, 300)

GRAEY = (155, 155, 155)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)


OPPNENTS_CARDS_PLACE = ((200, 75), (300, 75), (400, 75), (500, 75), (600, 75))
ES_PLACE = (400, 525)
CITIZERS_PLACE = ((200, 525), (300, 525), (500, 525), (600, 525))
START_PLACE = ((200, 525), (300, 525), (500, 525), (600, 525), (400, 525))
MY_CP = (400, 360)
OPP_CP = (400, 240)

ICON_IMG = 'img/exe_icon.png'
MENU_BG_IMG = 'img/menu_bg.png'
MENU_IMG = 'img/menu.png'
EMPEROR_IMG = 'img/emperor.png'
SLAVE_IMG = 'img/slave.png'
CITIZER_IMG = 'img/citizer.png'
FOX_IMG = 'img/fox.png'
SNAKE_IMG = 'img/snake.png'
URCHIN_IMG = 'img/urchin.png'
CARD_BACK_IMG_1 = 'img/card_back_1.png'
CARD_BACK_IMG_2 = 'img/card_back_2.png'
CARD_VIEW_IMG_1 = 'img/card_view_1.png'
CARD_VIEW_IMG_2 = 'img/card_view_2.png'
BG_IMG_1 = 'img/bg_1.png'
BG_IMG_2 = 'img/bg_2.png'
BG_IMG_3 = 'img/bg_3.png'
BG_VIEW_IMG_1 = 'img/bg_view_1.png'
BG_VIEW_IMG_2 = 'img/bg_view_2.png'
BG_VIEW_IMG_3 = 'img/bg_view_3.png'
CP_IMG_1 = 'img/cp_1.png'
CP_IMG_2 = 'img/cp_2.png'
CP_IMG_3 = 'img/cp_3.png'
CP_VIEW_IMG_1 = 'img/cp_view_1.png'
CP_VIEW_IMG_2 = 'img/cp_view_2.png'
CP_VIEW_IMG_3 = 'img/cp_view_3.png'
BOX_IMG_1 = 'img/box_1.png'
BOX_IMG_2 = 'img/box_2.png'
BOX_IMG_3 = 'img/box_3.png'
BOX_VIEW_IMG_1 = 'img/box_view_1.png'
BOX_VIEW_IMG_2 = 'img/box_view_2.png'
BOX_VIEW_IMG_3 = 'img/box_view_3.png'
BUTTON_ON_IMG = 'img/button_on.png'
BUTTON_OFF_IMG = 'img/button_off.png'
BTN_MUSIC_ON_IMG = 'img/btn_music_on.png'
BTN_MUSIC_OFF_IMG = 'img/btn_music_off.png'
BTN_EN_IMG ='img/btn_en.png'
BTN_RU_IMG = 'img/btn_ru.png'
PAPER_TITLE_IMG = 'img/paper_title.png'
PAPER_INFO_ON_IMG = 'img/paper_info_on.png'
PAPER_INFO_OFF_IMG = 'img/paper_info_off.png'
BTN_PREV_ON_IMG = 'img/btn_prev_on.png'
BTN_PREV_OFF_IMG = 'img/btn_prev_off.png'
BTN_NEXT_ON_IMG = 'img/btn_next_on.png'
BTN_NEXT_OFF_IMG = 'img/btn_next_off.png'
HEADING_SMALL_IMG = 'img/heading_small.png'
HEADING_BIG_LEFT_IMG = 'img/heading_big_left.png'
HEADING_BIG_RIGTH_IMG = 'img/heading_big_rigth.png'
FIELD_IP_LEFT_IMG = 'img/field_ip_left.png'
FIELD_IP_RIGTH_ON_IMG = 'img/field_ip_rigth_on.png'
FIELD_IP_RIGTH_OFF_IMG = 'img/field_ip_rigth_off.png'
BTN_CENTER_ON_IMG = 'img/btn_center_on.png'
BTN_CENTER_OFF_IMG = 'img/btn_center_off.png'
SQUARE_IMG = 'img/square.png'
POINT_IMG = 'img/point.png'
BTN_RIGHT_IMG = 'img/btn_right.png'
BTN_LEFT_IMG = 'img/btn_left.png'
DIALOGUE_WINDOW_IMG = 'img/dialogue_window.png'
TEXT_IMG = 'img/text.png'

DEFEAT_SOUND = 'music/defeat.mp3'
VICTORY_SOUND = 'music/victory.mp3'
SOUND_1 = 'music/sound_1.mp3'
SOUND_2 = 'music/sound_2.mp3'
SOUND_MENU = 'music/sound_menu.mp3'
SOUND_CLICK = 'music/sound_click.wav'

CAPTION = "ES-card"
EN = "en"
RU = "ru"
EMPEROR = 'EMPEROR'
SLAVE = 'SLAVE'
CITIZER = 'CITIZER'
WIN = 'WIN'
DEFEAT = "DEFEAT"
WAIT = "WAIT"
START = "START"
SHUTDOWN = "shutdown"
DRAW = 'DRAW'
CHANGE = "change"
CONNECTED = "connected"
NO_CONNECTED = "no_connected"
NORMAL = "normal"

GABRIOLA = 'fonts/gabriola.ttf'
TITLE_FONT = "fonts/vremyaboldItalic.ttf"
MONOTYPECORSIVA = 'fonts/monotypecorsiva.ttf'
ALGERIAN = "fonts/algerian.ttf"
ARIAL = "arial"